services:
  app:
    build: .
    container_name: app-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db-container
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=telegram_bot_db
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: