name: Cleanup Infrastructure

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-east-1
  TF_VERSION: 1.5.7

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Set script permissions
        run: chmod +x ./scripts/infra_destroy.sh

      - name: Destroy Infrastructure
        run: ./scripts/infra_destroy.sh
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
        working-directory: .