name: Cleanup Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (staging/production)'
        required: true
        default: 'staging'

env:
  AWS_REGION: ap-east-1
  TF_VERSION: 1.5.7

jobs:
  cleanup:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # Run cleanup script
      - name: Destroy Infrastructure
        run: ./infra_destroy.sh
        working-directory: .