name: Deploy Container

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!infra/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (staging/production)'
        required: true
        default: 'staging'

env:
  AWS_REGION: ap-east-1

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clean Maven Build
        run: ./mvnw clean
        working-directory: .

      - name: Build Maven Project
        run: ./mvnw package -DskipTests
        working-directory: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy Container
        run: ./scripts/container_deploy.sh
        working-directory: .