name: Infra Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "destroy" to confirm infrastructure destruction'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS Credentials (using access key/secret)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1

      # Step 3: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '>= 1.3.0'

      # Step 4: Validate destruction confirmation
      - name: Validate Destruction Confirmation
        run: |
          if [ "${{ github.event.inputs.confirm_destroy }}" != "destroy" ]; then
            echo "ERROR: You must input 'destroy' to confirm infrastructure destruction."
            exit 1
          fi

      # Step 5: Create terraform.tfvars with secrets
      - name: Create terraform.tfvars
        run: |
          cat <<EOF > infra/terraform.tfvars
          db_username = "${{ secrets.DB_USERNAME }}"
          db_password = "${{ secrets.DB_PASSWORD }}"
          chatgpt_token = "${{ secrets.CHATGPT_TOKEN }}"
          telegram_token = "${{ secrets.TELEGRAM_TOKEN }}"
          telegram_username = "${{ secrets.TELEGRAM_USERNAME }}"
          EOF

      # Step 6: Initialize Terraform
      - name: Initialize Terraform
        working-directory: infra
        run: terraform init
        env:
          AWS_DEFAULT_REGION: ap-east-1

      # Step 7: Run infra_destroy.sh
      - name: Destroy Infrastructure
        run: |
          chmod +x scripts/infra_destroy.sh
          ./scripts/infra_destroy.sh
        env:
          AWS_DEFAULT_REGION: ap-east-1

      # Step 8: Verify cleanup
      - name: Verify Resource Cleanup
        run: |
          echo "Checking for remaining resources..."
          vpc_count=$(aws ec2 describe-vpcs --region ap-east-1 --filters Name=tag:Name,Values=telegram-bot-vpc --query 'Vpcs | length(@)' --output text)
          rds_count=$(aws rds describe-db-instances --region ap-east-1 --db-instance-identifier telegram-bot-db --query 'DBInstances | length(@)' --output text 2>/dev/null || echo 0)
          ecs_count=$(aws ecs list-clusters --region ap-east-1 --query 'clusterArns | length(@)' --output text)
          ecr_count=$(aws ecr describe-repositories --region ap-east-1 --repository-names telegram-bot --query 'repositories | length(@)' --output text 2>/dev/null || echo 0)
          secrets_count=$(aws secretsmanager list-secrets --region ap-east-1 --query 'SecretList[?starts_with(Name, `telegram-bot/`)] | length(@)' --output text)
          
          echo "VPCs: $vpc_count"
          echo "RDS Instances: $rds_count"
          echo "ECS Clusters: $ecs_count"
          echo "ECR Repositories: $ecr_count"
          echo "Secrets: $secrets_count"
          
          if [ "$vpc_count" -gt 0 ] || [ "$rds_count" -gt 0 ] || [ "$ecs_count" -gt 0 ] || [ "$ecr_count" -gt 0 ] || [ "$secrets_count" -gt 0 ]; then
            echo "ERROR: Some resources still exist. Manual cleanup may be required."
            exit 1
          else
            echo "All resources successfully destroyed."
          fi
        env:
          AWS_DEFAULT_REGION: ap-east-1

      # Step 9: Clean up tfvars (always run, even if previous steps fail)
      - name: Clean up tfvars
        if: always()
        run: rm -f infra/terraform.tfvars